### ISSUE TITLE
Error When Try To Play A Music

### ISSUE THREAD

**Issue by bimaindrawans** [h00z3x/Lost-Music-V2#3]
Already fill lavalink information on .env
what should i do ?
```
   at Lavamusic.<anonymous> (file:///root/music/structures/Lavamusic.js:116:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/root/music/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/root/music/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/root/music/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
[10/24/2023] [3:32:35 PM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error: No nodes available, please add a node first
    at ShoukakuClient.getNode (file:///root/music/node_modules/shoukaku/dist/index.mjs:1271:13)
    at Queue.search (file:///root/music/structures/Queue.js:51:43)
    at InteractionCreate.run (file:///root/music/events/client/InteractionCreate.js:152:53)
    at Lavamusic.<anonymous> (file:///root/music/structures/Lavamusic.js:116:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/root/music/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/root/music/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/root/music/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
[10/24/2023] [3:32:36 PM] [InteractionCreate.js] [Lavamusic] › ✖  error     Error: No nodes available, please add a node first
    at ShoukakuClient.getNode (file:///root/music/node_modules/shoukaku/dist/index.mjs:1271:13)
    at Play.run (file:///root/music/commands/music/Play.js:46:106)
    at InteractionCreate.run (file:///root/music/events/client/InteractionCreate.js:142:31)
    at Lavamusic.<anonymous> (file:///root/music/structures/Lavamusic.js:116:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/root/music/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/root/music/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/root/music/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
[10/24/2023] [3:32:37 PM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error: No nodes available, please add a node first
    at ShoukakuClient.getNode (file:///root/music/node_modules/shoukaku/dist/index.mjs:1271:13)
    at Queue.search (file:///root/music/structures/Queue.js:51:43)
    at InteractionCreate.run (file:///root/music/events/client/InteractionCreate.js:152:53)
    at Lavamusic.<anonymous> (file:///root/music/structures/Lavamusic.js:116:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/root/music/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/root/music/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/root/music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/root/music/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)

```

**Comment by bimaindrawans** [comment]
sorry my mistake forgot to put port on the link
but when i tried to play a song, the bot only showing music is playing but didn't transmit any audio to the voice channel
