### ISSUE TITLE
Cannot Play a Song  "An error occurred: TypeError: Cannot read properties of null (reading 'loadType') 

### ISSUE THREAD

**Issue by bimaindrawans** [h00z3x/Lost-Music-V2#5]
[1/15/2024] [5:02:59 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:00 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - NA is ready!
[1/15/2024] [5:03:00 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:01 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:01 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - NA is ready!
[1/15/2024] [5:03:01 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:02 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:02 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:03 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:03 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:04 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:04 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:05 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:05 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:06 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:06 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:07 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:07 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:08 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:08 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:09 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:10 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:10 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:11 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:11 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:12 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:12 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:13 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:13 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:14 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Lexnet.cc - EU is ready!
[1/15/2024] [5:03:14 PM] [InteractionCreate.js] [Lavamusic] › ✖  error     TypeError: Cannot read properties of null (reading 'loadType') 
    at Play.run (file:///home/runner/Lost-Music-V2/commands/music/Play.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InteractionCreate.run (file:///home/runner/Lost-Music-V2/events/client/InteractionCreate.js:142:17)```
    
    when i try to play a song showed up 
    ```
     TypeError: Cannot read properties of null (reading 'loadType') 
    at Play.run (file:///home/runner/Lost-Music-V2/commands/music/Play.js:49:21)```

**Comment by bimaindrawans** [comment]
[1/15/2024] [5:10:54 PM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> PrismaClientKnownRequestError: 
  Invalid `prisma.setup.findUnique()` invocation:
  
  
  The table `main.Setup` does not exist in the current database.
      at xc.handleRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:7326)
      at xc.handleAndLogRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6755)
      at xc.request (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6345)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async updateSetup (file:///home/runner/Lost-Music-V2/utils/SetupSystem.js:150:17)
      at async QueueEnd.run (file:///home/runner/Lost-Music-V2/events/player/QueueEnd.js:24:9) {
    code: 'P2021',
    clientVersion: '4.16.2',
    meta: { table: 'main.Setup' }
  }
} reason: PrismaClientKnownRequestError: 
Invalid `prisma.setup.findUnique()` invocation:


The table `main.Setup` does not exist in the current database.
    at xc.handleRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:7326)
    at xc.handleAndLogRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6755)
    at xc.request (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6345)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateSetup (file:///home/runner/Lost-Music-V2/utils/SetupSystem.js:150:17)
    at async QueueEnd.run (file:///home/runner/Lost-Music-V2/events/player/QueueEnd.js:24:9) {
  code: 'P2021',
  clientVersion: '4.16.2',
  meta: { table: 'main.Setup' }
}

**Comment by h00z3x** [comment]
> [1/15/2024] [5:02:59 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:00 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - NA is ready! [1/15/2024] [5:03:00 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:01 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:01 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - NA is ready! [1/15/2024] [5:03:01 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:02 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:02 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:03 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:03 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:04 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:04 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:05 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:05 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:06 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:06 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:07 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:07 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:08 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:08 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:09 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:10 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:10 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:11 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:11 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:12 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:12 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:13 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:13 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:14 PM] [NodeConnect.js] [Lavamusic] › ✔ success Node Lexnet.cc - EU is ready! [1/15/2024] [5:03:14 PM] [InteractionCreate.js] [Lavamusic] › ✖ error TypeError: Cannot read properties of null (reading 'loadType') at Play.run (file:///home/runner/Lost-Music-V2/commands/music/Play.js:49:21) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async InteractionCreate.run (file:///home/runner/Lost-Music-V2/events/client/InteractionCreate.js:142:17)```
> 
> ```
> when i try to play a song showed up 
> ```
>  TypeError: Cannot read properties of null (reading 'loadType') 
> at Play.run (file:///home/runner/Lost-Music-V2/commands/music/Play.js:49:21)```
> ```

The LavaLinks I have added in `lavalinks.json` are old. it's best to remove them or replace them. Also just in case: `.env` lavalink config has priority over the `lavalinks.json`.

**Comment by h00z3x** [comment]
> [1/15/2024] [5:10:54 PM] [antiCrash.js] [Lavamusic] › ✖ error Unhandled Rejection at: Promise { PrismaClientKnownRequestError: Invalid `prisma.setup.findUnique()` invocation:
> 
> The table `main.Setup` does not exist in the current database. at xc.handleRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:7326) at xc.handleAndLogRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6755) at xc.request (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6345) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async updateSetup (file:///home/runner/Lost-Music-V2/utils/SetupSystem.js:150:17) at async QueueEnd.run (file:///home/runner/Lost-Music-V2/events/player/QueueEnd.js:24:9) { code: 'P2021', clientVersion: '4.16.2', meta: { table: 'main.Setup' } } } reason: PrismaClientKnownRequestError: Invalid `prisma.setup.findUnique()` invocation:
> 
> The table `main.Setup` does not exist in the current database. at xc.handleRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:7326) at xc.handleAndLogRequestError (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6755) at xc.request (/home/runner/Lost-Music-V2/node_modules/@prisma/client/runtime/binary.js:232:6345) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async updateSetup (file:///home/runner/Lost-Music-V2/utils/SetupSystem.js:150:17) at async QueueEnd.run (file:///home/runner/Lost-Music-V2/events/player/QueueEnd.js:24:9) { code: 'P2021', clientVersion: '4.16.2', meta: { table: 'main.Setup' } }

I suggest you to do the step 4 and 5 and give me some feedback if possible:

Generate Prisma
```
npx prisma generate
```
Generate Database
```
npx prisma migrate dev
```
