### ISSUE TITLE
The song doesn't play and quits immediately

### ISSUE THREAD

**Issue by KimPig** [h00z3x/Lost-Music-V2#6]
**Describe the bug**
The song doesn't play and quits immediately
Even if I enter the song name into a song-only channel, the song does not play and ends immediately.

**To Reproduce**
1. Setup Music Channel
2. Play any songs

**Additional context**
I don't know if it's a related login, but I get this error when I start the bot.
There was a recent update to lavalink. Could this be a related issue?
```[5/19/2024] [4:43:56 AM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> SyntaxError: Invalid URL: wss://ip:port
      at initAsClient (/volume1/Lost-Music-V2/node_modules/ws/lib/websocket.js:675:13)
      at new WebSocket (/volume1/Lost-Music-V2/node_modules/ws/lib/websocket.js:85:7)
      at Node.connect (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:1007:15)
      at ShoukakuClient.addNode (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:1249:10)
      at DiscordJS.ready (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:178:20)
      at Lavamusic.<anonymous> (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:200:42)
      at Object.onceWrapper (node:events:628:26)
      at Lavamusic.emit (node:events:525:35)
      at WebSocketManager.triggerClientReady (/volume1/Lost-Music-V2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:388:17)
      at WebSocketManager.checkShardsReady (/volume1/Lost-Music-V2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:371:10)
} reason: SyntaxError: Invalid URL: wss://ip:port
    at initAsClient (/volume1/Lost-Music-V2/node_modules/ws/lib/websocket.js:675:13)
    at new WebSocket (/volume1/Lost-Music-V2/node_modules/ws/lib/websocket.js:85:7)
    at Node.connect (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:1007:15)
    at ShoukakuClient.addNode (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:1249:10)
    at DiscordJS.ready (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:178:20)
    at Lavamusic.<anonymous> (file:///volume1/Lost-Music-V2/node_modules/shoukaku/dist/index.mjs:200:42)
    at Object.onceWrapper (node:events:628:26)
    at Lavamusic.emit (node:events:525:35)
    at WebSocketManager.triggerClientReady (/volume1/Lost-Music-V2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:388:17)
    at WebSocketManager.checkShardsReady (/volume1/Lost-Music-V2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:371:10)
```

**Comment by Arad00ak** [comment]
I think this has been fixed in the new update try it and tell us if anything happens 😁
